#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: H.Miyazawa
  history:
  - version: 1.0.0
    date: '2025-06-27'
    author: H.Miyazawa
    comment: OptiServe用のデータベース設計
  - version: 1.1.0
    date: '2025-07-10'
    author: H.Miyazawa
    comment: 'インデックス情報及び外部キー情報を追加'
  - version: 1.2.0
    date: '2025-08-22'
    author: H.Miyazawa
    comment: 'ユーザーIDをintegerからtextに変更。'

#- tableinfo ----------------------------------------------
table_name: map_user_entity
old_table_name: user_entity_link
description: ユーザーと組織（医療機関・ディーラー・メーカー）の紐付け
#- columns info -------------------------------------------
columns:
  - name: entity_type
    description: 組織の種別
    data_type: integer
    primary_key: true
    nullable: false
    comment: '1: 医療機関, 2: ディーラー, 3: メーカー'

  - name: entity_relation_id
    description: 連携する組織ID
    data_type: integer
    primary_key: true
    nullable: false
    comment: '連携する組織のID。entity_typeに応じて医療機関ID、ディーラーID、メーカーIDが入る'
    references:
      - table: mst_medical_facility
        column: medical_id
        enforced: false  # DB制約無し
        on_delete: restrict  # restrict, cascade, set null, no action
        on_update: restrict
        comment: 'entity_type=1.医療機関の場合、mst_medical_facilityテーブルのmedical_idを参照。'
      - table: mst_dealer
        column: dealer_id
        enforced: false  # DB制約無し
        on_delete: restrict  # restrict, cascade, set null, no action
        on_update: restrict
        comment: 'entity_type=2.ディーラーの場合、mst_dealerテーブルのdealer_idを参照。'
      - table: mst_manufacturer
        column: manufacturer_id
        enforced: false  # DB制約無し
        on_delete: restrict  # restrict, cascade, set null, no action
        on_update: restrict
        comment: 'entity_type=3.メーカーの場合、mst_manufacturerテーブルのmanufacturer_idを参照。'
      - table: mst_medical_facility
        column: medical_id
        enforced: false  # DB制約無し
        on_delete: restrict  # restrict, cascade, set null, no action
        on_update: restrict
        comment: 'entity_type=1.医療機関の場合、mst_medical_facilityテーブルのmedical_idを参照。'

  - name: entity_name
    description: 組織名
    data_type: text
    primary_key: false
    nullable: false
    comment: '表示用に利用する組織名称'

  - name: entity_address_postal_code
    description: 組織の郵便番号
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の郵便番号（オプション）'

  - name: entity_address_prefecture
    description: 組織の都道府県
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の都道府県（オプション）'

  - name: entity_address_city
    description: 組織の市区町村
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の市区町村（オプション）'

  - name: entity_address_line1
    description: 組織の住所1
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の町名以降・番地（オプション）'

  - name: entity_address_line2
    description: 組織の住所2
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の建物名等（オプション）'

  - name: entity_phone_number
    description: 組織の電話番号
    data_type: text
    primary_key: false
    nullable: true
    comment: '組織の電話番号（オプション）'

  - name: notification_email_list
    description: 通知メールアドレス
    data_type: json
    primary_key: false
    nullable: false
    comment: 'ユーザーアカウントのメールアドレスは必須。それ以外にレポート配布の通知等の情報を受け取るメールアドレスをJSON形式で格納します。複数のメールアドレスを登録することができます。'

  - name: count_reportout_classification
    description: レポート公開の分類数
    data_type: integer
    primary_key: false
    nullable: false
    comment: '医療機関向けレポートに、出力させる機器分類数。'

  - name: analiris_classification_level
    description: 分析レポートの分類レベル
    data_type: integer
    primary_key: false
    nullable: false
    comment: '分析レポートで使用する機器分類のレベル。1: 大分類、2: 中分類、3: 小分類。'

  - name: reg_user_id
    description: 登録ユーザーID
    data_type: text
    primary_key: false
    nullable: false
    comment: 'このレコードの登録を行ったユーザーのID。'
    references:
      table: m_mst_user
      column: user_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict

  - name: regdate
    description: データ作成日
    data_type: timestamp
    primary_key: false
    nullable: false
    comment: null

  - name: update_user_id
    description: 更新ユーザーID
    data_type: text
    primary_key: false
    nullable: false
    comment: 'このレコードの更新を行ったユーザーのID。'
    references:
      table: m_mst_user
      column: user_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict

  - name: lastupdate
    description: 最終更新日
    data_type: timestamp
    primary_key: false
    nullable: false
    comment: null

#- indexes info -------------------------------------------
indexes:
  - name: idx_map_user_entity_type_id
    old_name: idx_user_entity
    columns: [entity_type, entity_relation_id]
    unique: false
    note: '組織種別と連携組織IDの複合インデックス'
